"""create initial tables

Revision ID: edb6e6301ce5
Revises: 
Create Date: 2026-03-10 13:40:05.482350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'edb6e6301ce5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_urbani',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('STRADA', 'LAMPIONE', 'PARCO', 'SEMAFORO', 'TOMBINO', 'ALTRO', name='tipoasset'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('useful_life_years', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operatori',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OPERATORE', 'TECNICO', 'RESPONSABILE', 'ADMIN', name='ruolooperatore'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('segnalazioni',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unique_code', sa.String(length=12), nullable=False),
    sa.Column('category', sa.Enum('STRADALE', 'ILLUMINAZIONE', 'VERDE_PUBBLICO', 'RIFIUTI', 'SEGNALETICA', 'FOGNATURA', 'ALTRO', 'DA_VERIFICARE', name='categoriasegnalazione'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('APERTA', 'IN_LAVORAZIONE', 'COMPLETATA', 'RIFIUTATA', name='statosegnalazione'), nullable=False),
    sa.Column('ai_suggested_category', sa.String(length=50), nullable=True),
    sa.Column('ai_priority_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('citizen_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    op.create_table('squadre',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('type', sa.Enum('ORDINARIO', 'STRAORDINARIO', 'EMERGENZA', name='tipointervento'), nullable=False),
    sa.Column('status', sa.Enum('PIANIFICATO', 'IN_CORSO', 'COMPLETATO', 'ANNULLATO', name='statointervento'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('squadra_id', sa.UUID(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_urbani.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['squadra_id'], ['squadre.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('squadra_operatori',
    sa.Column('squadra_id', sa.UUID(), nullable=False),
    sa.Column('operatore_id', sa.UUID(), nullable=False),
    sa.Column('is_team_leader', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operatore_id'], ['operatori.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squadra_id'], ['squadre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('squadra_id', 'operatore_id')
    )
    op.create_table('segnalazione_interventi',
    sa.Column('segnalazione_id', sa.UUID(), nullable=False),
    sa.Column('intervento_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intervento_id'], ['interventi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segnalazione_id'], ['segnalazioni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segnalazione_id', 'intervento_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segnalazione_interventi')
    op.drop_table('squadra_operatori')
    op.drop_table('interventi')
    op.drop_table('squadre')
    op.drop_table('segnalazioni')
    op.drop_table('operatori')
    op.drop_table('asset_urbani')
    # ### end Alembic commands ###